package com.fertilesound.oblique.obliquestrategies;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

public class ObliqueStrategiesStrings {

    private List<String> strategies = new ArrayList(134);

    public ObliqueStrategiesStrings() {
        this.strategies.add("Remove specifics and convert to ambiguities ");
        this.strategies.add("Think of the radio");
        this.strategies.add("Don't be frightened of clichés");
        this.strategies.add("What is the reality of the situation?");
        this.strategies.add("Are there sections? Consider transitions");
        this.strategies.add("Turn it upside down");
        this.strategies.add("Allow an easement (an easement is the abandonment of a stricture)");
        this.strategies.add("Simple subtraction");
        this.strategies.add("Remove specifics and convert to ambiguities");
        this.strategies.add("Go slowly all the way round the outside");
        this.strategies.add("A line has two sides ");
        this.strategies.add("Infinitesimal gradations");
        this.strategies.add("Make an exhaustive list of everything you might do and do the last thing on the list");
        this.strategies.add("Into the impossible");
        this.strategies.add("Ask people to work against their better judgment");
        this.strategies.add("Take away the elements in order of apparent non-importance");
        this.strategies.add("Change instrument roles");
        this.strategies.add("Accretion");
        this.strategies.add("Disconnect from desire");
        this.strategies.add("Emphasize repetitions");
        this.strategies.add("Don't be afraid of things because they're easy to do ");
        this.strategies.add("Is there something missing?");
        this.strategies.add("Don't be frightened to display your talents");
        this.strategies.add("Breathe more deeply");
        this.strategies.add("Honor thy error as a hidden intention");
        this.strategies.add("Only one element of each kind");
        this.strategies.add("Use unqualified people");
        this.strategies.add("How would you have done it?");
        this.strategies.add("Emphasize differences");
        this.strategies.add("Do nothing for as long as possible");
        this.strategies.add("Bridges: -build -burn");
        this.strategies.add("Water");
        this.strategies.add("You don't have to be ashamed of using your own ideas");
        this.strategies.add("Tidy up");
        this.strategies.add("Do the words need changing?");
        this.strategies.add("Ask your body");
        this.strategies.add("Make a sudden, destructive unpredictable action; incorporate");
        this.strategies.add("Consult other sources");
        this.strategies.add("Use an unacceptable color");
        this.strategies.add("Humanize something free of error");
        this.strategies.add("Use filters");
        this.strategies.add("Balance the consistency principle with the inconsistency principle");
        this.strategies.add("Fill every beat with something");
        this.strategies.add("Discard an axiom");
        this.strategies.add("What wouldn't you do?");
        this.strategies.add("Decorate, decorate");
        this.strategies.add("Do nothing for as long as possible");
        this.strategies.add("Listen to the quiet voice");
        this.strategies.add("Is it finished?");
        this.strategies.add("Put in earplugs");
        this.strategies.add("Give the game away");
        this.strategies.add("Reverse");
        this.strategies.add("Abandon normal instruments");
        this.strategies.add("Use fewer notes");
        this.strategies.add("Repetition is a form of change");
        this.strategies.add("Give way to your worst impulse");
        this.strategies.add("Trust in the you of now");
        this.strategies.add("What would your closest friend do?");
        this.strategies.add("Distorting time");
        this.strategies.add("Make a blank valuable by putting it in an exquisite frame");
        this.strategies.add("The inconsistency principle");
        this.strategies.add("Ghost echoes");
        this.strategies.add("You can only make one dot at a time");
        this.strategies.add("Just carry on");
        this.strategies.add("(Organic) machinery");
        this.strategies.add("Don't break the silence");
        this.strategies.add("Discover the recipes you are using and abandon them");
        this.strategies.add("Cascades");
        this.strategies.add("Courage!");
        this.strategies.add("What mistakes did you make last time?");
        this.strategies.add("You are an engineer");
        this.strategies.add("Consider different fading systems");
        this.strategies.add("Mute and continue");
        this.strategies.add("It is quite possible (after all)");
        this.strategies.add("Don't stress one thing more than another");
        this.strategies.add("Remove ambiguities and convert to specifics");
        this.strategies.add("Look at the order in which you do things");
        this.strategies.add("Go outside. Shut the door.");
        this.strategies.add("Do we need holes?");
        this.strategies.add("Cluster analysis");
        this.strategies.add("Work at a different speed");
        this.strategies.add("Do something boring");
        this.strategies.add("Define an area as ‘safe’ and use it as an anchor");
        this.strategies.add("Overtly resist change");
        this.strategies.add("Accept advice");
        this.strategies.add("Look closely at the most embarrassing details and amplify them");
        this.strategies.add("Mechanicalize something idiosyncratic");
        this.strategies.add("Emphasize the flaws");
        this.strategies.add("Remember those quiet evenings");
        this.strategies.add("Take a break");
        this.strategies.add("The tape is now the music");
        this.strategies.add("Short circuit (example: a man eating peas with the idea that they will improve his virility shovels them straight into his lap)");
        this.strategies.add("Use an old idea");
        this.strategies.add("Destroy: -nothing -the most important thing");
        this.strategies.add("Change nothing and continue with immaculate consistency");
        this.strategies.add("Imagine the music as a moving chain or caterpillar");
        this.strategies.add("Intentions: -credibility of -nobility of -humility of");
        this.strategies.add("Imagine the music as a set of disconnected events");
        this.strategies.add("Imagine the piece as a set of disconnected events");
        this.strategies.add("What are you really thinking about just now? Incorporate.");
        this.strategies.add("Children's voices: -speaking -singing");
        this.strategies.add("Assemble some of the instruments in a group and treat the group");
        this.strategies.add("Shut the door and listen from outside");
        this.strategies.add("Is the tuning appropriate?");
        this.strategies.add("Look at a very small object, look at its centre");
        this.strategies.add("Feedback recordings into an acoustic situation");
        this.strategies.add("Towards the insignificant");
        this.strategies.add("Simply a matter of work");
        this.strategies.add("Not building a wall but making a brick");
        this.strategies.add("Revaluation (a warm feeling)");
        this.strategies.add("Disciplined self-indulgence");
        this.strategies.add("The most important thing is the thing most easily forgotten");
        this.strategies.add("Idiot glee");
        this.strategies.add("Be extravagant");
        this.strategies.add("State the problem in words as clearly as possible");
        this.strategies.add("Always first steps");
        this.strategies.add("Question the heroic approach");
        this.strategies.add("Always give yourself credit for having more than personality");
        this.strategies.add("Faced with a choice, do both");
        this.strategies.add("Tape your mouth");
        this.strategies.add("Twist the spine");
        this.strategies.add("Get your neck massaged");
        this.strategies.add("Do the washing up");
        this.strategies.add("Convert a melodic element into a rhythmic element");
        this.strategies.add("Spectrum analysis");
        this.strategies.add("Lowest common denominator check: -single beat -single note -single riff");
        this.strategies.add("Listen in total darkness, or in a very large room, very quietly");
        this.strategies.add("Would anybody want it?");
        this.strategies.add("Retrace your steps");
        this.strategies.add("Go to an extreme, move back to a more comfortable place");
        this.strategies.add("Once the search is in progress, something will be found");
        this.strategies.add("Only a part, not the whole");
        this.strategies.add("From nothing to more than nothing");
        this.strategies.add("Be less critical more often");
    }

    public String getRandomStrategy() {
        return (String)this.strategies.get(ThreadLocalRandom.current().nextInt(1, this.strategies.size()));
    }
}
